### ISSUE TITLE
bug in fastwaves DppDz

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/dawn#190]
Here https://github.com/cosunae/clang-gridtools/blob/fast_waves_sc/src/dycore/fast_waves_sc.cpp#L387

The computation of `sum(i + 1, DppDzS)` is moved before the comp of DppDzS

```
     const gridtools::clang::float_type __local_sum_6727 =
          (__tmp_DppDzS_3726_ijcache[ijcacheindex + 1] + __tmp_DppDzS_3726_ijcache[ijcacheindex]);
      if (((bool)false == (int)0)) {
        __tmp_DppDzS_3726_ijcache[ijcacheindex] =
            (((wgtOneSided_kcache[2] * __ldg(&(__tmp_ppMinusDiv_3727[idx111]))) +
              (wgtOneSided_kcache[1] * __ldg(&(__tmp_ppMinusDiv_3727[idx111 + stride_111_2 * -1])))) +
             (wgtOneSided_kcache[0] * __ldg(&(__tmp_ppMinusDiv_3727[idx111 + stride_111_2 * -2]))));
        const gridtools::clang::float_type __local_dp_dx_rho_4363 =
            (__ldg(&(frac1RhoDx[idx111])) *
             (__local_delta_6724 - (__ldg(&(dz_lam_u_half[idx111])) * __local_sum_6727)));
        u[idx111] =
            (__ldg(&(u_pos[idx111])) + (globals_.dts * (__ldg(&(du_dt_slow[idx111])) - __local_dp_dx_rho_4363)));
      }
```
but furthermore there is a missing syncthreads between computing DppDz and consuming it

**Comment by cosunae** [comment]
The problem is solved with this workaround 
there is a data dependency inside the conditional on DppDz, not detected
https://github.com/cosunae/clang-gridtools/commit/7c1728b90755ddc5f243520a51dd98577acde837

**Comment by Stagno** [comment]
By compiling the following simplified stencil that tries to reproduce the same behavior
```
#include "gridtools/clang_dsl.hpp"
using namespace gridtools::clang;

globals {
  bool x = false;
};

stencil_function sum {
  offset off;
  storage data;

  Do { return data[off] + data; }
};

stencil test {

  storage b,c,d;
  var z, a;

  Do {
    vertical_region(k_end, k_end) {
      if(x == 0) {
        z = a * b;
        const double e = d * (c * sum(i + 1, z));
      }
    }
  }
};
```
with the argument `-fdump-split-dags` also the dag dump breaks. This is due to the fact that pointer `oldGraph` is null when used here: https://github.com/MeteoSwiss-APN/dawn/blob/2ccc1843b89d6646694c6fada808fd8281647e33/src/dawn/Optimizer/PassStageSplitter.cpp#L72

**Comment by Stagno** [comment]
The data dependency seems correctly recognized as you can see from the following dump obtained for the example I presented in the comment before:
[dependency graph of accesses](https://github.com/MeteoSwiss-APN/dawn/files/3241595/output.pdf)

The issue is with the splitting process in general. In `PassStageSplitter::run(...)` (), when iterating through the statements of a DoMethod, the statements inside the block of a conditional statement are not considered. `stmtIndex` goes only through the (direct) children of the DoMethod.
https://github.com/MeteoSwiss-APN/dawn/blob/2ccc1843b89d6646694c6fada808fd8281647e33/src/dawn/Optimizer/PassStageSplitter.cpp#L62
The detection of Read-before-Write conflicts inside an If block works correctly because, when inserting an If statement to the graph with `DependencyGraphAccesses::insertStatementAccessesPair(...)`, this inserts all the children of the If block. But then the `stmtIndex` at which the split is tried is the one of the If statement. This triggers the assertion failure: `thisDoMethod.getChildren().size() >= 2` because `Stage::split(...)` tries to split a 1-statement stage.
I think that `PassStageSplitter` and `Stage::split(...)` require a non-trivial rewrite.

**Comment by twicki** [comment]
You bring up a couple of points. I'll try to address them one by one as they are mostly independent:
## Your toy example
If I run  fast-waves dppz I get an assertion in the Stage reordering rather than the stage splitting algorithm. Irrespective of if this is the correct issue to bring this up, we should follow up on your error.

## Printing of the split graphs:
This is clearly an oversight and  should be solved in a quite quick fashion: If I look at the code, it seems like L71-73 should not even be there and the printing should only happen in L95-97. It seems to have slipped the radar during a refactoring.

## Data Dependency Issue:
I think you're on the right track here. This is exactly the issue. The `stmtIndex` points to the if-stmt and the `doMethod` has only one child.
So the question here becomes: What is the expected result? is it 
```
Stage_0: 
    if(condition){
      stmt_0
    }
Stage_1:
    if(condition){
       stmt_1
    }
```
block statements have an ordered list of their substatements stored. If we find this, I think we can resolve the issue withouth too much work as all the data is there and we just need to split this list and recreate the if-clause. 
https://github.com/MeteoSwiss-APN/dawn/blob/2ccc1843b89d6646694c6fada808fd8281647e33/src/dawn/IIR/StatementAccessesPair.h#L55

I agree that this fix is not trivial but I don't see a mayor rewrite required.

**Comment by Stagno** [comment]
We the latest merged PR #206, when there is a data dependency inside an if, a diagnostic error is generated. This doesn't solve the issue but warns the user to find another way.
